apiVersion: 1

datasources:
  - name: NovaGuardDB
    uid: NovaGuardDB
    type: postgres
    access: proxy
    url: postgres:5432
    database: novaguard_db
    user: novaguard
    secureJsonData:
      password: novaguard_secret
    jsonData:
      database: novaguard_db
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
